name: syntrack
description: A time tracking and booking tool

publish_to: 'none'

version: 1.3.5+5

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.8.1
  auto_route: ^5.0.4
  autocomplete_textfield_ns: ^2.0.0
  built_collection: ^5.1.0
  built_value: ^8.1.0
  copy_with_extension: ^5.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  http: ^0.13.3
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  just_debounce_it: ^4.0.0+2
  path_provider: ^2.0.2
  sizer: ^2.0.13
  uuid: ^3.0.4
  # flutter_typeahead: ^4.3.6
  flutter_typeahead:
    git:
      url: https://github.com/enoy19/flutter_typeahead.git
      ref: streamed

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  built_value_generator: ^8.1.0
  copy_with_extension_gen: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "res/logo/syntrack_logo_padded.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "res/logo/syntrack_logo.png"
    background_color: "#FF5250"
    theme_color: "#1923DC"
  windows:
    generate: false
    image_path: "res/logo/syntrack_logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "res/logo/syntrack_logo_padded.png"