display_name: synTrack
generic_name: synTrack

icon: res/logo/syntrack_logo.png

keywords:
  - synTrack
  - timetracking
  - time tracking
  - booking
  - redmine


categories:
  - Utility

startup_notify: false

include: []