name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-gen:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Cache pub-cache
        uses: actions/cache@v2
        with:
          path: ./.pub-cache
          key: ${{ github.run_id }}-pub-cache
          restore-keys: |
            ${{ github.run_id }}-pub-cache
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Upload generated files
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: |
            lib/**/*.g.dart
            lib/**/*.gr.dart
          retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    needs: build-gen
    container:
      image: cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: generated-files
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends cmake ninja-build clang build-essential pkg-config libgtk-3-dev liblzma-dev lcov zip
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux --release
      - run: |
          pushd build/linux/x64/release/bundle
          zip -r 'synTrack.zip' *
          popd
          mv build/linux/x64/release/bundle/synTrack.zip .
      - name: Upload synTrack.zip
        uses: actions/upload-artifact@v2
        with:
          name: synTrack-linux
          path: synTrack.zip
          retention-days: 1

  package-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Download synTrack.zip
        uses: actions/download-artifact@v2
        with:
          name: synTrack-linux
      - run: apk update
      - run: apk add curl
      - run: 'curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type:application/octet-stream" --data-binary @synTrack.zip "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=synTrack.zip"'

  build-android:
    runs-on: ubuntu-latest
    needs: build-gen
    container:
      image: cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: generated-files
      - run: flutter pub get
      - run: flutter build apk --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk ./synTrack.apk
      - name: Upload synTrack.apk
        uses: actions/upload-artifact@v2
        with:
          name: synTrack-android
          path: synTrack.apk
          retention-days: 1

  package-android:
    runs-on: ubuntu-latest
    needs: build-android
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Download synTrack.apk
        uses: actions/download-artifact@v2
        with:
          name: synTrack-android
      - run: apk update
      - run: apk add curl
      - run: 'curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type:application/octet-stream" --data-binary @synTrack.apk "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=synTrack.apk"'
