name: Release

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev locate rpm patchelf fuse libfuse2
      - run: |
         wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
         chmod +x appimagetool
         sudo mv appimagetool /usr/local/bin/
      - run: dart pub global activate flutter_distributor
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      # the release command lines below fails to find the AppImage in the file system because it searches in a
      # case insensitive way (*.appimage instead of *.AppImage). This is my workaround. Issue: https://github.com/leanflutter/flutter_distributor/issues/118
      - run: flutter_distributor package --platform linux --targets appimage
      - run: flutter_distributor publish --targets=github --github-repo-owner=synyx --github-repo-name=synTrack --path="$(echo ./dist/*/*.AppImage)"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: flutter_distributor release --name release --skip-jobs linux-appimage,darwin-dmg
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g appdmg
      - run: dart pub global activate flutter_distributor
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter_distributor release --name release --jobs darwin-dmg
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
