name: Release

on:
  workflow_run:
    workflows: 
      - Build
    branches:
      - main
    types: 
      - completed
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_run' 
      && github.event.workflow_run.conclusion == 'success'
      && startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev locate rpm patchelf fuse libfuse2
      - run: |
         wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
         chmod +x appimagetool
         sudo mv appimagetool /usr/local/bin/
      - run: dart pub global activate flutter_distributor
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter_distributor release --name release --skip-jobs linux-appimage # TODO: find out why app image file is not found
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

